version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "14:40"
  ignore:
  - dependency-name: xo
    versions:
    - "> 0.25.3"
  - dependency-name: xo
    versions:
    - ">= 0.32.a, < 0.33"
  rebase-strategy: disabled
