name: All the CI

on:
  push:
    branches:
      - release
      - master
      - renovate/*
  pull_request:
    branches:
      '*'

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Unit Tests
      run: |
        yarn install --frozen-lockfile
        NODE_ENV=testing yarn knex migrate:latest
        node scripts/initialize-test-db.js
        yarn test:unit
        node _commands/post-test.js
      env:
        CI: true
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        TEST_NAME: unit
        FORCE_COLOR: 3
  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Integration Tests
      run: |
        mkdir -p lib/frontend/client/release
        echo '<title>gradebook</title>' > lib/frontend/client/release/index.html
        yarn install --frozen-lockfile
        NODE_ENV=testing yarn knex migrate:latest
        node scripts/initialize-test-db.js
        yarn test:functional
        node _commands/post-test.js
      env:
        CI: true
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        TEST_NAME: integration
        FORCE_COLOR: 3
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Lint
      run: |
        yarn install --frozen-lockfile
        yarn lint
        yarn typecheck
        node _commands/post-test.js
      env:
        CI: true
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        TEST_NAME: lint
        FORCE_COLOR: 3
