name: All the CI

on:
  push:
    branches:
      - release
      - master
      - renovate/*
    tags-ignore:
      - '**'
  pull_request:
    branches:
      '*'

env:
  FORCE_COLOR: 3

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: gradebook/actions/actions/setup@master
      with:
        node-version: 18.20.x
    - name: Install Dependencies and setup
      run: |
        yarn install --frozen-lockfile --prefer-offline
        NODE_ENV=testing yarn knex migrate:latest
        node scripts/initialize-test-db.js
    - name: Unit Tests
      run: yarn test:unit
    - name: Trigger Webhook
      run: yarn release-utils hook
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        TEST_NAME: unit
        REQUIRE_PUSH: 'true'
        REQUIRE_BRANCH: release
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NODE_ENV: testing
    steps:
    - uses: gradebook/actions/actions/setup@master
      with:
        node-version: 18.20.x
    - name: Configure Dependencies
      run: |
        yarn install --frozen-lockfile --prefer-offline
        mkdir -p lib/frontend/client/release
        echo '<head><title>gradebook</title></head>' > lib/frontend/client/release/index.html
    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
        sudo mysql -u root -proot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'toor'"
    - name: Bootstrap Database
      run: |
        # Do not initialize the fake host with seed data so we can make sure host matching is respected
        database__connection__database=host_fake yarn knex migrate:latest
        database__connection__database=host_real yarn knex migrate:latest
        database__connection__database=host_real node scripts/initialize-test-db.js
    - name: Functional Tests
      run: yarn test:functional
      env:
        database__connection__database: host_real
    - name: Trigger Webhook
      run: yarn release-utils hook
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        TEST_NAME: integration
        REQUIRE_PUSH: 'true'
        REQUIRE_BRANCH: release
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: gradebook/actions/actions/setup@master
      with:
        node-version: 18.20.x
    - name: Install dependencies and setup
      run: yarn install --frozen-lockfile --prefer-offline
    - name: Lint and Typecheck
      run: |
        yarn lint
        yarn typecheck
    - name: Trigger Webhook
      run: yarn release-utils hook
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        TEST_NAME: lint
        REQUIRE_PUSH: 'true'
        REQUIRE_BRANCH: release
