name: All the CI

on:
  push:
    branches:
      - release
      - master
      - renovate/*
  pull_request:
    branches:
      '*'

env:
  FORCE_COLOR: 3

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: lts/*
        cache: yarn
    - name: Install Dependencies and setup
      run: |
        yarn install --frozen-lockfile
        NODE_ENV=testing yarn knex migrate:latest
        node scripts/initialize-test-db.js
    - name: Unit Tests
      run: yarn test:unit
    - name: Trigger Webhook
      run: yarn release-utils hook
      with:
        require_push: 'true'
        branch: release
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        TEST_NAME: unit
  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: lts/*
        cache: yarn
    - name: Install dependencies and setup
      run: |
        mkdir -p lib/frontend/client/release
        echo '<title>gradebook</title>' > lib/frontend/client/release/index.html
        yarn install --frozen-lockfile
        NODE_ENV=testing yarn knex migrate:latest
        node scripts/initialize-test-db.js
    - name: Functional Tests
      run: yarn test:functional
    - name: Trigger Webhook
      run: yarn release-utils hook
      with:
        require_push: 'true'
        branch: release
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        TEST_NAME: integration
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: lts/*
        cache: yarn
    - name: Install dependencies and setup
      run: |
        yarn install --frozen-lockfile
    - name: Lint and Typecheck
      run: |
        yarn lint
        yarn typecheck
    - name: Trigger Webhook
      run: yarn release-utils hook
      with:
        require_push: 'true'
        branch: release
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        TEST_NAME: lint
