name: Contract Tests

on:
  workflow_dispatch:
    inputs:
      server_ref:
        description: Git ref to pull for server
        default: 'master'
      client_ref:
        description: Git ref to pull for client
        default: 'master'
  push:
    branches:
      - release
      - contract-testing
  schedule:
    - cron: '0 2 * * 0' # Every Sunday at 2:00 UTC (~9 PM CST)

jobs:
  contract:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NODE_ENV: testing
    steps:
    - name: Configure ENV
      run: |
        RAW_CLIENT_REF=${{ github.event.inputs.client_ref }}
        RAW_SERVER_REF=${{ github.event.inputs.server_ref }}
        MID_SERVER_REF=${RAW_SERVER_REF:-$GITHUB_SHA}
        echo "CLIENT_REF=${RAW_CLIENT_REF:-master}" >> $GITHUB_ENV
        echo "SERVER_REF=${MID_SERVER_REF:-master}" >> $GITHUB_ENV
    - uses: gradebook/actions/actions/setup@master
      with:
        git-ref: ${{ env.SERVER_REF }}
    - name: Install Dependencies and Setup
      run: |
        yarn install --frozen-lockfile --prefer-offline
        yarn knex migrate:latest
        node scripts/initialize-test-db.js
    - name: Clone client ref
      run: |
        eval $(ssh-agent -s)
        ssh-add - <<< "$CLIENT_DEPLOY_KEY"
        cd lib/frontend/client
        git init
        git remote add origin $CLIENT_REMOTE_URL
        git fetch origin ${{ env.CLIENT_REF }}
        git checkout ${{ env.CLIENT_REF }}
      shell: bash
      env:
        CLIENT_DEPLOY_KEY: ${{ secrets.GRADEBOOK_CLIENT_READONLY_DEPLOY_KEY }}
        CLIENT_REMOTE_URL: ${{ secrets.GRADEBOOK_CLIENT_REMOTE_URL }}
    - name: Print refs
      run: |
        echo "Server Ref: `git log -1 --pretty='format:%H (%s)'`"
        cd lib/frontend/client
        echo "Client Ref: `git log -1 --pretty='format:%H (%s)'`"
      shell: bash
    - name: Run Tests
      run: yarn test:contract
